{"c2c771a19162e1a7f39df202fcfdc4ce":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":3,"unknown":0,"total":9},"items":[{"uid":"c37f243d9312807e","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/c37f243d9312807e","status":"passed","time":{"start":1691591500993,"stop":1691591509559,"duration":8566}},{"uid":"a3078700399b3b38","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/a3078700399b3b38","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1dc10b90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591292992,"stop":1691591292992,"duration":0}},{"uid":"facafa02fb52f525","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/facafa02fb52f525","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562cf9b7f613 <unknown>\n#1 0x562cf98ab537 <unknown>\n#2 0x562cf98d6588 <unknown>\n#3 0x562cf98d35d9 <unknown>\n#4 0x562cf9913643 <unknown>\n#5 0x562cf9912d8f <unknown>\n#6 0x562cf990a803 <unknown>\n#7 0x562cf98de68b <unknown>\n#8 0x562cf98df42e <unknown>\n#9 0x562cf9b40c28 <unknown>\n#10 0x562cf9b44af7 <unknown>\n#11 0x562cf9b4f01c <unknown>\n#12 0x562cf9b45723 <unknown>\n#13 0x562cf9b14457 <unknown>\n#14 0x562cf9b69628 <unknown>\n#15 0x562cf9b697b7 <unknown>\n#16 0x562cf9b78483 <unknown>\n#17 0x7fcf4b6a6b43 <unknown>","time":{"start":1691590769989,"stop":1691590772144,"duration":2155}},{"uid":"e87a444fea995f52","reportUrl":"https://SerovVl.github.io/RedBasset/13//#testresult/e87a444fea995f52","status":"passed","time":{"start":1691478565774,"stop":1691478573479,"duration":7705}},{"uid":"ff0be894724b4f72","reportUrl":"https://VISerov.github.io/RedBasset/12//#testresult/ff0be894724b4f72","status":"passed","time":{"start":1691476970922,"stop":1691476979278,"duration":8356}},{"uid":"2b203bd4a22726ce","reportUrl":"https://VISerov.github.io/RedBasset/11//#testresult/2b203bd4a22726ce","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='none', port=80): Max retries exceeded with url: /session (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f13ad461210>: Failed to resolve 'none' ([Errno -3] Temporary failure in name resolution)\"))","time":{"start":1691476107671,"stop":1691476107671,"duration":0}},{"uid":"1cfd6a7639699854","reportUrl":"https://VISerov.github.io/RedBasset/8//#testresult/1cfd6a7639699854","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f52dce39310>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691353789961,"stop":1691353789961,"duration":0}},{"uid":"5aa0b7b8da65f965","reportUrl":"https://VISerov.github.io/RedBasset/5//#testresult/5aa0b7b8da65f965","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='192.168.1.5', port=8080): Max retries exceeded with url: /wd/hub/session (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7fa99c1f5710>, 'Connection to 192.168.1.5 timed out. (connect timeout=None)'))","time":{"start":1691317417466,"stop":1691317417466,"duration":0}},{"uid":"97038f88132b0a5a","reportUrl":"https://VISerov.github.io/RedBasset/4//#testresult/97038f88132b0a5a","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x557a6a755783 <unknown>\n#1 0x557a6a481917 <unknown>\n#2 0x557a6a4ac978 <unknown>\n#3 0x557a6a4a99c9 <unknown>\n#4 0x557a6a4e9a13 <unknown>\n#5 0x557a6a4e915f <unknown>\n#6 0x557a6a4e0bd3 <unknown>\n#7 0x557a6a4b4a7b <unknown>\n#8 0x557a6a4b581e <unknown>\n#9 0x557a6a716e98 <unknown>\n#10 0x557a6a71ad67 <unknown>\n#11 0x557a6a72532c <unknown>\n#12 0x557a6a71b993 <unknown>\n#13 0x557a6a6ea827 <unknown>\n#14 0x557a6a73f8a8 <unknown>\n#15 0x557a6a73fa36 <unknown>\n#16 0x557a6a74e5f3 <unknown>\n#17 0x7fc26d69db43 <unknown>","time":{"start":1690892299787,"stop":1690892301764,"duration":1977}}]},"6ef0da2265c6089c7f795e499ed70723":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"f91130cc840054a8","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/f91130cc840054a8","status":"passed","time":{"start":1691591724759,"stop":1691591725709,"duration":950}},{"uid":"5f3ef335f3ff32d3","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/5f3ef335f3ff32d3","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1d920b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591294034,"stop":1691591294034,"duration":0}},{"uid":"a8c88ea73263597d","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/a8c88ea73263597d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55af84ab4613 <unknown>\n#1 0x55af847e0537 <unknown>\n#2 0x55af8480b588 <unknown>\n#3 0x55af848085d9 <unknown>\n#4 0x55af84848643 <unknown>\n#5 0x55af84847d8f <unknown>\n#6 0x55af8483f803 <unknown>\n#7 0x55af8481368b <unknown>\n#8 0x55af8481442e <unknown>\n#9 0x55af84a75c28 <unknown>\n#10 0x55af84a79af7 <unknown>\n#11 0x55af84a8401c <unknown>\n#12 0x55af84a7a723 <unknown>\n#13 0x55af84a49457 <unknown>\n#14 0x55af84a9e628 <unknown>\n#15 0x55af84a9e7b7 <unknown>\n#16 0x55af84aad483 <unknown>\n#17 0x7fc353a7fb43 <unknown>","time":{"start":1691590780738,"stop":1691590780738,"duration":0}}]},"6d4e1e17354f91bc82ebeba1ea206bd3":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"a73299d4721820be","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/a73299d4721820be","status":"passed","time":{"start":1691591520934,"stop":1691591532525,"duration":11591}},{"uid":"31f83ea7fea4b300","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/31f83ea7fea4b300","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1d8b4390>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591293281,"stop":1691591293281,"duration":0}},{"uid":"ed3818980383a63d","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/ed3818980383a63d","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55f006a07613 <unknown>\n#1 0x55f006733537 <unknown>\n#2 0x55f00675e588 <unknown>\n#3 0x55f00675b5d9 <unknown>\n#4 0x55f00679b643 <unknown>\n#5 0x55f00679ad8f <unknown>\n#6 0x55f006792803 <unknown>\n#7 0x55f00676668b <unknown>\n#8 0x55f00676742e <unknown>\n#9 0x55f0069c8c28 <unknown>\n#10 0x55f0069ccaf7 <unknown>\n#11 0x55f0069d701c <unknown>\n#12 0x55f0069cd723 <unknown>\n#13 0x55f00699c457 <unknown>\n#14 0x55f0069f1628 <unknown>\n#15 0x55f0069f17b7 <unknown>\n#16 0x55f006a00483 <unknown>\n#17 0x7ff649055b43 <unknown>","time":{"start":1691590773185,"stop":1691590773185,"duration":0}}]},"df3d929e7a986ded5f73b7eda0461b28":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"a2ac543e22579cc2","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/a2ac543e22579cc2","status":"broken","statusDetails":"selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id\nStacktrace:\n#0 0x55a74201b783 <unknown>\n#1 0x55a741d47766 <unknown>\n#2 0x55a741d79f26 <unknown>\n#3 0x55a741da6d06 <unknown>\n#4 0x55a741da2e8d <unknown>\n#5 0x55a741da25f5 <unknown>\n#6 0x55a741d14da3 <unknown>\n#7 0x55a741fdce98 <unknown>\n#8 0x55a741fe0d67 <unknown>\n#9 0x55a741feb32c <unknown>\n#10 0x55a741fe1993 <unknown>\n#11 0x55a741fb0827 <unknown>\n#12 0x55a741d132d1 <unknown>\n#13 0x7f9001e12d90 <unknown>","time":{"start":1691591582708,"stop":1691591610377,"duration":27669}},{"uid":"ed7d55431a2520d5","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/ed7d55431a2520d5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1d61bfd0>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591293462,"stop":1691591293462,"duration":0}},{"uid":"8b46d4663eeabbe5","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/8b46d4663eeabbe5","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x55fb18e3e613 <unknown>\n#1 0x55fb18b6a537 <unknown>\n#2 0x55fb18b95588 <unknown>\n#3 0x55fb18b925d9 <unknown>\n#4 0x55fb18bd2643 <unknown>\n#5 0x55fb18bd1d8f <unknown>\n#6 0x55fb18bc9803 <unknown>\n#7 0x55fb18b9d68b <unknown>\n#8 0x55fb18b9e42e <unknown>\n#9 0x55fb18dffc28 <unknown>\n#10 0x55fb18e03af7 <unknown>\n#11 0x55fb18e0e01c <unknown>\n#12 0x55fb18e04723 <unknown>\n#13 0x55fb18dd3457 <unknown>\n#14 0x55fb18e28628 <unknown>\n#15 0x55fb18e287b7 <unknown>\n#16 0x55fb18e37483 <unknown>\n#17 0x7f6f238f5b43 <unknown>","time":{"start":1691590775079,"stop":1691590775079,"duration":0}}]},"b2ee2e3f48a79cf21b441017c2fb9a24":{"statistic":{"failed":0,"broken":2,"skipped":0,"passed":1,"unknown":0,"total":3},"items":[{"uid":"639f2e739a74888b","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/639f2e739a74888b","status":"passed","time":{"start":1691591680378,"stop":1691591702940,"duration":22562}},{"uid":"9e4d567d806780b5","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/9e4d567d806780b5","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1d649b50>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591293834,"stop":1691591293834,"duration":0}},{"uid":"88cdf19abba467f8","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/88cdf19abba467f8","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x555cc0c7d613 <unknown>\n#1 0x555cc09a9537 <unknown>\n#2 0x555cc09d4588 <unknown>\n#3 0x555cc09d15d9 <unknown>\n#4 0x555cc0a11643 <unknown>\n#5 0x555cc0a10d8f <unknown>\n#6 0x555cc0a08803 <unknown>\n#7 0x555cc09dc68b <unknown>\n#8 0x555cc09dd42e <unknown>\n#9 0x555cc0c3ec28 <unknown>\n#10 0x555cc0c42af7 <unknown>\n#11 0x555cc0c4d01c <unknown>\n#12 0x555cc0c43723 <unknown>\n#13 0x555cc0c12457 <unknown>\n#14 0x555cc0c67628 <unknown>\n#15 0x555cc0c677b7 <unknown>\n#16 0x555cc0c76483 <unknown>\n#17 0x7feff707bb43 <unknown>","time":{"start":1691590778859,"stop":1691590778859,"duration":0}}]},"b270d0aa38c18209a6d611a883cc0568":{"statistic":{"failed":1,"broken":2,"skipped":0,"passed":0,"unknown":0,"total":3},"items":[{"uid":"1970d45955997b81","reportUrl":"https://SerovVl.github.io/RedBasset/16//#testresult/1970d45955997b81","status":"failed","statusDetails":"selene.core.exceptions.TimeoutException: Message: \n\nTimed out after 4s, while waiting for:\nbrowser.element(('css selector', '[data-spec=\"podcaster-author-tab-settings\"]')).click\n\nReason: NoSuchElementException: Message: no such element: Unable to locate element: {\"method\":\"css selector\",\"selector\":\"[data-spec=\"podcaster-author-tab-settings\"]\"}\n  (Session info: chrome=115.0.5790.102); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception\nStacktrace:\n#0 0x561ae0d34783 <unknown>\n#1 0x561ae0a60917 <unknown>\n#2 0x561ae0a9f31b <unknown>\n#3 0x561ae0a9f411 <unknown>\n#4 0x561ae0ada674 <unknown>\n#5 0x561ae0abfe2d <unknown>\n#6 0x561ae0ad80d9 <unknown>\n#7 0x561ae0abfbd3 <unknown>\n#8 0x561ae0a93a7b <unknown>\n#9 0x561ae0a9481e <unknown>\n#10 0x561ae0cf5e98 <unknown>\n#11 0x561ae0cf9d67 <unknown>\n#12 0x561ae0d0432c <unknown>\n#13 0x561ae0cfa993 <unknown>\n#14 0x561ae0cc9827 <unknown>\n#15 0x561ae0d1e8a8 <unknown>\n#16 0x561ae0d1ea36 <unknown>\n#17 0x561ae0d2d5f3 <unknown>\n#18 0x7f2375da1b43 <unknown>\n\nScreenshot: file:///home/runner/.selene/screenshots/1691591498674/1691591498675.png\nPageSource: file:///home/runner/.selene/screenshots/1691591498674/1691591498675.html","time":{"start":1691591636488,"stop":1691591652439,"duration":15951}},{"uid":"bdde2803feb21a27","reportUrl":"https://SerovVl.github.io/RedBasset/15//#testresult/bdde2803feb21a27","status":"broken","statusDetails":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4444): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7c1d7abc90>: Failed to establish a new connection: [Errno 111] Connection refused'))","time":{"start":1691591293659,"stop":1691591293659,"duration":0}},{"uid":"9e96f62b7ebba730","reportUrl":"https://SerovVl.github.io/RedBasset/14//#testresult/9e96f62b7ebba730","status":"broken","statusDetails":"selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.\n  (unknown error: DevToolsActivePort file doesn't exist)\n  (The process started from chrome location /opt/google/chrome/chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)\nStacktrace:\n#0 0x562215916613 <unknown>\n#1 0x562215642537 <unknown>\n#2 0x56221566d588 <unknown>\n#3 0x56221566a5d9 <unknown>\n#4 0x5622156aa643 <unknown>\n#5 0x5622156a9d8f <unknown>\n#6 0x5622156a1803 <unknown>\n#7 0x56221567568b <unknown>\n#8 0x56221567642e <unknown>\n#9 0x5622158d7c28 <unknown>\n#10 0x5622158dbaf7 <unknown>\n#11 0x5622158e601c <unknown>\n#12 0x5622158dc723 <unknown>\n#13 0x5622158ab457 <unknown>\n#14 0x562215900628 <unknown>\n#15 0x5622159007b7 <unknown>\n#16 0x56221590f483 <unknown>\n#17 0x7f1d601ceb43 <unknown>","time":{"start":1691590776962,"stop":1691590776962,"duration":0}}]}}